Micah dev
hudsonb/turf.kt pull request #33
Opened 2019-03-26 05:29 UTC by Ixw123

Measurement:area implemented, yet to be tested or well documented. Let me know what you would like me to change or just change it or comment on this or in the code yourself. Thanks

2019-03-26 15:30 UTC, hudsonb requested changes

2019-03-26 15:30 UTC, hudsonb commented on src/main/kotlin/org/turfkt/Measurement.kt
> +fun Geometry.area() = calculateArea(this)
Provide the return type explicitly: `fun Geometry.area(): Double`

2019-03-26 15:30 UTC, hudsonb commented on src/main/kotlin/org/turfkt/Measurement.kt
> +fun Polygon.area() = calculateArea(this)
Remove, this is handled by `fun Geometry.area(): Double`

2019-03-26 15:30 UTC, hudsonb commented on src/main/kotlin/org/turfkt/Measurement.kt
> +fun MultiPolygon.area() = calculateArea(this)
Remove this is handled by `fun Geometry.area(): Double`

2019-03-26 15:30 UTC, hudsonb commented on src/main/kotlin/org/turfkt/Measurement.kt
> +//fun main() {
Remove

2019-03-26 15:30 UTC, hudsonb commented on src/main/kotlin/org/turfkt/Measurement.kt
> +            //val size = geom.coordinates.size
Remove

2019-03-26 15:30 UTC, hudsonb commented on src/main/kotlin/org/turfkt/Measurement.kt
> +            //val size = geom.coordinates.size
Remove

2019-03-26 15:30 UTC, hudsonb commented on src/main/kotlin/org/turfkt/Measurement.kt
> +            for (i in 0..(geom.coordinates.size - 1)) {
Use `for(i in 0 until geom.coordinates.size`) or `for(i in geom.coordinates.indices)`

2019-03-26 15:30 UTC, hudsonb commented on src/main/kotlin/org/turfkt/Measurement.kt
> +    //val coordSize = coordinates.size
Remove

2019-03-26 15:30 UTC, hudsonb commented on src/main/kotlin/org/turfkt/Measurement.kt
> +        for (i: Int in 1..(coordinates.size - 1)){
Type declaration on `i` is not needed. Use `for(i in 1 until coordinates.size)`

2019-03-26 15:30 UTC, hudsonb commented on src/main/kotlin/org/turfkt/Measurement.kt
> +        for (i in 0..(coordinateLength - 1)) {
Use `until`

2019-03-28 01:22 UTC, hudsonb requested changes
The changes to .gitignore should not be included, otherwise looks good.

Can you back out the changes to .gitignore?

2019-03-28 03:22 UTC, Ixw123 commented
I can definitly tru I'm not quite sure how to do that

On Wed, Mar 27, 2019, 21:22 Brian Hudson <notifications@github.com> wrote:

> *@hudsonb* requested changes on this pull request.
>
> The changes to .gitignore should not be included, otherwise looks good.
>
> Can you back out the changes to .gitignore?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hudsonb/turf.kt/pull/33#pullrequestreview-219797024>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AONKblN5iwzimg6gPngXiLn54ml1E5FRks5vbBk-gaJpZM4cKodK>
> .
>

2019-03-28 13:30 UTC, hudsonb commented
You can just revert the changes and commit.

I'd rebase the branch and edit the commit that added the modifications, but
that'll probably take you awhile to do if you aren't familar with the
process. I'm going to squash the branch before committing anyways.

On Wed, Mar 27, 2019 at 11:22 PM Micah Church <notifications@github.com>
wrote:

> I can definitly tru I'm not quite sure how to do that
>
> On Wed, Mar 27, 2019, 21:22 Brian Hudson <notifications@github.com> wrote:
>
> > *@hudsonb* requested changes on this pull request.
> >
> > The changes to .gitignore should not be included, otherwise looks good.
> >
> > Can you back out the changes to .gitignore?
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/hudsonb/turf.kt/pull/33#pullrequestreview-219797024
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe-auth/AONKblN5iwzimg6gPngXiLn54ml1E5FRks5vbBk-gaJpZM4cKodK
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/hudsonb/turf.kt/pull/33#issuecomment-477431949>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABTAaB_0_Bwr3O6icncku91UggRtthAZks5vbDV0gaJpZM4cKodK>
> .
>

2019-04-02 17:13 UTC, merged