Micah dev
hudsonb/turf.kt pull request #37
Opened 2019-05-04 07:26 UTC by Ixw123

Envelope is working need to ensure that bbox is working just need to fix some indexing for coordinates will have working by sometime tomorrow, will do and finish circle by then as well

2019-05-04 11:15 UTC, hudsonb commented
The BBox class is immutable, you aren't supposed to be able to modify those
values post construction. Create vars to track south/West/north/East then
simply construct the BBox at the end with those bars.

On Sat, May 4, 2019 at 3:26 AM Micah Church <notifications@github.com>
wrote:

> Envelope is working need to ensure that bbox is working just need to fix
> some indexing for coordinates will have working by sometime tomorrow, will
> do and finish circle by then as well
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/hudsonb/turf.kt/pull/37
> Commit Summary
>
>    - Added Measurements.kt
>    - Merge branch 'master' into Micah-Dev
>    - still trying to get it to work
>    - Measure.kt compiles
>    - Merge branch 'master' into Micah-Dev
>    - Nevermind the previous statment
>    - Compiles but has yet to be tested
>    - Cleaned up the code a bit
>    - Merge branch 'master' into Micah-Dev
>    - Applied suggested changes of the PR
>    - Merge branch 'master' into Micah-Dev
>    - Merge branch 'master' into Micah-Dev
>    - Changed name of previous file
>    - Extra directory removed
>    - Envelope.kt
>    - Implemented Envelope.kt
>    - Taken from main
>    - Also taken from main
>
> File Changes
>
>    - *M* src/main/kotlin/geojsonkt/BBox.kt
>    <https://github.com/hudsonb/turf.kt/pull/37/files#diff-0> (85)
>    - *A* src/main/kotlin/turfkt/Center.kt
>    <https://github.com/hudsonb/turf.kt/pull/37/files#diff-1> (9)
>    - *A* src/main/kotlin/turfkt/Envelope.kt
>    <https://github.com/hudsonb/turf.kt/pull/37/files#diff-2> (17)
>
> Patch Links:
>
>    - https://github.com/hudsonb/turf.kt/pull/37.patch
>    - https://github.com/hudsonb/turf.kt/pull/37.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hudsonb/turf.kt/pull/37>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAKMA2AWIMZC4JV5TH7INXDPTU3CXANCNFSM4HKYJZKA>
> .
>

2019-05-04 11:26 UTC, Ixw123 commented
Oh okay I think I know how I need to change it then. I'll make the changes
after i get some shuteye. So the bbox extension functions essentially would
fill in the bbox value of and only if it is null right?

On Sat, May 4, 2019, 07:15 Brian Hudson <notifications@github.com> wrote:

> The BBox class is immutable, you aren't supposed to be able to modify those
> values post construction. Create vars to track south/West/north/East then
> simply construct the BBox at the end with those bars.
>
> On Sat, May 4, 2019 at 3:26 AM Micah Church <notifications@github.com>
> wrote:
>
> > Envelope is working need to ensure that bbox is working just need to fix
> > some indexing for coordinates will have working by sometime tomorrow,
> will
> > do and finish circle by then as well
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/hudsonb/turf.kt/pull/37
> > Commit Summary
> >
> > - Added Measurements.kt
> > - Merge branch 'master' into Micah-Dev
> > - still trying to get it to work
> > - Measure.kt compiles
> > - Merge branch 'master' into Micah-Dev
> > - Nevermind the previous statment
> > - Compiles but has yet to be tested
> > - Cleaned up the code a bit
> > - Merge branch 'master' into Micah-Dev
> > - Applied suggested changes of the PR
> > - Merge branch 'master' into Micah-Dev
> > - Merge branch 'master' into Micah-Dev
> > - Changed name of previous file
> > - Extra directory removed
> > - Envelope.kt
> > - Implemented Envelope.kt
> > - Taken from main
> > - Also taken from main
> >
> > File Changes
> >
> > - *M* src/main/kotlin/geojsonkt/BBox.kt
> > <https://github.com/hudsonb/turf.kt/pull/37/files#diff-0> (85)
> > - *A* src/main/kotlin/turfkt/Center.kt
> > <https://github.com/hudsonb/turf.kt/pull/37/files#diff-1> (9)
> > - *A* src/main/kotlin/turfkt/Envelope.kt
> > <https://github.com/hudsonb/turf.kt/pull/37/files#diff-2> (17)
> >
> > Patch Links:
> >
> > - https://github.com/hudsonb/turf.kt/pull/37.patch
> > - https://github.com/hudsonb/turf.kt/pull/37.diff
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/hudsonb/turf.kt/pull/37>, or mute the thread
> > <
> https://github.com/notifications/unsubscribe-auth/AAKMA2AWIMZC4JV5TH7INXDPTU3CXANCNFSM4HKYJZKA
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hudsonb/turf.kt/pull/37#issuecomment-489317815>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ADRUU3TJMPO2A5QEPAKSX33PTVV6LANCNFSM4HKYJZKA>
> .
>

2019-05-06 12:31 UTC, hudsonb requested changes

2019-05-06 12:31 UTC, hudsonb commented on src/main/kotlin/geojsonkt/BBox.kt
> +
Remove commented out code

2019-05-06 12:31 UTC, hudsonb commented on src/main/kotlin/geojsonkt/BBox.kt
> +        is MultiPoint -> throw UnsupportedOperationException("Can not calculate BBox of MultiPoint Geometry type: ${this::class.java.name}")
Add support for bbox on MultiPoint. Even if turf.js doesn't support it, it seems easy enough to implement.

2019-05-06 12:31 UTC, hudsonb commented on src/main/kotlin/geojsonkt/BBox.kt
> +            // Need to look at this and figure out what to do to be able to set these values properly
Remove comment

2019-05-06 12:31 UTC, hudsonb commented on src/main/kotlin/turfkt/Midpoint.kt
> +    val units = "" // not sure what to have this default to but i noticed it was not used at all in this instance
Remove `units`. It should be an optional parameter in `destination`, so you don't need to provide since it.

2019-05-06 12:31 UTC, hudsonb commented on src/main/kotlin/turfkt/Midpoint.kt
> +}
1. Remove unneeded `this` references throughout the file.

2. `Point.midpoint` should just defer to `Position.midpoint`:
```
fun Point.midpoint(to: Position): Position =
    coordinate.midpoint(to)  
```

Same for `Feature<Point>.midpoint`. We don't want to repeat the logic for calculating the midpoint multiple times, it becomes harder to maintain.

2019-05-06 12:31 UTC, hudsonb commented on src/main/kotlin/turfkt/CenterOfMass.kt
> +import geojsonkt.*
This file does not compile. You'll have to get it at least compiling before this PR can be merged.

2019-05-07 15:53 UTC, closed without merging